title: Î’Î¹Î²Î»Î¹Î¿ÏƒÎ·Î¼ÎµÎ¹ÏŽÏƒÎµÎ¹Ï‚
description: Î£ÎºÎ­ÏˆÎµÎ¹Ï‚ Î³Î¹Î± Î²Î¹Î²Î»Î¯Î± Ï€Î¿Ï… Î´Î¹Î¬Î²Î±ÏƒÎ± ðŸ“š

locale: el
lang: el

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
